### ISSUE TITLE
Migrate to Swift 3 07-25 (develop branch).

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Swift-cfenv#15]
Please, see recipe here: https://github.com/IBM-Swift/Swift-cfenv/wiki/Updating-Swift-cfenv

**Comment by rfdickerson** [comment]
Should we just skip this one and move to 7-29 instead?

**Comment by shmuelk** [comment]
I would have also thought so, but the 07/29 driver is having some issues. See https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20160725/002579.html
