### ISSUE TITLE
Evaluate using Foundation framework’s JSONSerialization

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/Swift-cfenv#27]
Let's evaluate the possibility of using Foundation framework’s JSONSerialization instead of SwiftyJSON. For more details, see https://developer.apple.com/swift/blog/?id=37.

**Comment by BDHernand** [comment]
Ok i change the following method:

    public func getServiceURL(spec: String, replacements: [String: Any]) -> String? {
    var substitutions: [String: Any] = replacements
    let service = getService(spec: spec)
    guard let credentials = service?.credentials else {
      return nil
    }

    guard let url: String =
      credentials[substitutions["url"] ?? "url"] ?? credentials["uri"]
      else {
      return nil
    }

    substitutions["url"] = nil
    guard var parsedURL = URLComponents(string: url) else {
      return nil
    }

    // Set replacements in a predefined order
    // Before, we were just iterating over the keys in the JSON object,
    // but unfortunately the order of the keys returned were different on
    // OS X and Linux, which resulted in different outcomes.
    if let user = substitutions["user"] {
       parsedURL.user = (user as! String)
    }
    if let password = substitutions["password"] {
      parsedURL.password = (password as! String)
    }
    if let port = substitutions["port"] {
      parsedURL.port = (port as! Int)
    }
    if let host = substitutions["host"] {
      parsedURL.host = (host as! String)
    }
    if let scheme = substitutions["scheme"] {
      parsedURL.scheme = (scheme as! String)
    }
    if let query = substitutions["query"] {
      parsedURL.query = (query as! String)
    }
    if let queryItems = (substitutions["queryItems"] as! [String: Any]?) {
      var urlQueryItems: [URLQueryItem] = []
      for (_, QI) in queryItems {
        var queryItem : [String: Any] = (QI as! [String: Any])
        let name = (queryItem["name"] as! String)
        let urlQueryItem = URLQueryItem(name: name, value: (queryItem["value"] as! String))
        urlQueryItems.append(urlQueryItem)
      }
      if urlQueryItems.count > 0 {
        parsedURL.queryItems = urlQueryItems
      }
    }
    // These are being ignored at the moment
    // if let fragment = substitutions["fragment"].string {
    //   parsedURL.fragment = fragment
    // }
    // if let path = substitutions["path"].string {
    //   parsedURL.path = path
    // }
    return parsedURL.string
  }


its blowing up on:

/Users/brianhernandez/devops/Swift-cfenv/Sources/CloudFoundryEnv/AppEnv.swift:172:32: error: cannot subscript a value of type 'inout [String : Any]' (aka 'inout Dictionary<String, Any>')
      credentials[substitutions["url"] ?? "url"] ?? credentials["uri"]
                  ~~~~~~~~~~~~~^
<unknown>:0: error: build had 1 command failures

I cant quite seem to understand what that line is doing

**Comment by BDHernand** [comment]
my branch if you want to look at it is issue.remove_swifty

**Comment by rolivieri** [comment]
Just made the change to fix that compilation error and pushed it to your branch.
