### ISSUE TITLE
Doesn't build on the Swift 3.1 toolchains - NSRegularExpression

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Swift-cfenv#51]
Because there was a change made to the `swift-3.1-branch` and others in the master branch, currently this does not build on anything but Swift 3.0.2. This is because of the name change back to NSRegularExpression from RegularExpression.

**Comment by christiancompton** [comment]
This seems to work fine for both 3.1 and 3.0.2.  Test cases included below:

3.1:
![screen shot 2017-02-01 at 9 39 34 am](https://cloud.githubusercontent.com/assets/18534315/22513728/b56c9f74-e862-11e6-9a03-a80fde95c0a4.png)

3.0.2: 
![screen shot 2017-02-01 at 9 27 36 am](https://cloud.githubusercontent.com/assets/18534315/22513742/bf3772d6-e862-11e6-966f-ef3a9d44c4fb.png)

@rolivieri Given this compatibility, I will tag this version `2.0.4`.  The bigger issue here is that the automated tests cannot build properly with the development snapshot branch - I am currently pursuing this problem.

**Comment by christiancompton** [comment]
This issue is blocked because the 3.1 development snapshot does not compile on 14.04, breaking CI tests.

**Comment by christiancompton** [comment]
I am closing this issue because the 3.1 development snapshot is no longer needed for swift-cfenv at this time.
